# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 99757b4aa65430d2061c789fb37dd90155a7193da017a428b8426db7e5b2d59e7a414aacbe143b5986ce98990c39d21aecbc5edfc8aab17c833cfb10da5ef865

test:
  secret_key_base: 60ab45c86f72a61f91cef0f0e09b80258619ea164b1f22a04d2df07a4a3671fbda75090a21f9dcb80bc9bdadcec85002d2b477cc8088d5cf8bec0f8a5043e624

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
